# Based on https://github.com/pypa/python-manylinux-demo/blob/master/.travis.yml

language: python  # just for twine

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE
  - pip install twine

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - twine upload --skip-existing wheelhouse/* -r https://testpypi.python.org/pypi --repository-url https://testpypi.python.org/pypi
